### ISSUE TITLE
파이어베이스 세팅

### ISSUE THREAD

**Issue by winter223** [MoyeoRun/MoyeoRun_Android#1]
- 모여런 안드로이드 앱을 파이어베이스와 연동합니다.
- Real/Debug 프로젝트를 따로 운용합니다. (권한이 없으면 건훈님께 요청)
  - [Moyeorun-Debug](https://console.firebase.google.com/u/0/project/moyeorun-8da0f)
  - [Moyeorun](https://console.firebase.google.com/u/0/project/moyeorun-18349)
- 파이어베이스 API 를 사용할 것을 염두에 두고, 미리 release, debug 용 공용 키를 생성하여 등록해둡니다.
  - 빌드 시 해당 키를 사용하도록 하고, 키에 대한 정보는 별도 properties 파일로 관리하여 공개 레포지토리에는 올려두지 않습니다.
- Crashlytics SDK 를 설치합니다.

**Comment by heechokim** [comment]
모여런 안드로이드 프로젝트의 첫 이슈네요오~~ 👏🏻 👏🏻 👏🏻
